title: MalariaGEN vector data user guide
author: MalariaGEN
copyright: "2021"
logo: images/logo.png
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/malariagen/vector-data
  path_to_book              : docs
  branch                    : master
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://gke.mybinder.org"
html:
  use_repository_button : true
  use_issues_button: true
 
